[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tuktuk_maintenance"
version = "0.1.0"
description = "Maintenance Management Addon for Sunny TukTuk Fleet"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "Yuda Media", email = "yuda@graphicshop.co.ke"},
]
dependencies = []
optional-dependencies = { dev = ["../tuktuk_management"] }


[project.urls]
Homepage = "https://github.com/yudamedia/tuktuk-maintenance"
Repository = "https://github.com/yudamedia/tuktuk-maintenance.git"
